//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamilla.Network {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NetworkStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kamilla.Network.NetworkStrings", typeof(NetworkStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0?plural-en:byte:bytes}.
        /// </summary>
        public static string bytes {
            get {
                return ResourceManager.GetString("bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} {1?plural-en:byte:bytes} read.
        /// </summary>
        public static string BytesRead {
            get {
                return ResourceManager.GetString("BytesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-&gt;S.
        /// </summary>
        public static string CH_C2S {
            get {
                return ResourceManager.GetString("CH_C2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string CH_Length {
            get {
                return ResourceManager.GetString("CH_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string CH_Number {
            get {
                return ResourceManager.GetString("CH_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-&gt;C.
        /// </summary>
        public static string CH_S2C {
            get {
                return ResourceManager.GetString("CH_S2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticks.
        /// </summary>
        public static string CH_Ticks {
            get {
                return ResourceManager.GetString("CH_Ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string CH_Time {
            get {
                return ResourceManager.GetString("CH_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRPD v1.
        /// </summary>
        public static string NetworkLog_KRPDv1 {
            get {
                return ResourceManager.GetString("NetworkLog_KRPDv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRPD v2.
        /// </summary>
        public static string NetworkLog_KRPDv2 {
            get {
                return ResourceManager.GetString("NetworkLog_KRPDv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser: {0}.
        /// </summary>
        public static string ParserClass {
            get {
                return ResourceManager.GetString("ParserClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in parser:.
        /// </summary>
        public static string ParserException {
            get {
                return ResourceManager.GetString("ParserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Protocol.
        /// </summary>
        public static string Protocol_Default {
            get {
                return ResourceManager.GetString("Protocol_Default", resourceCulture);
            }
        }
    }
}
