//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkLogViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkLogViewer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Files.
        /// </summary>
        public static string BinaryFiles {
            get {
                return ResourceManager.GetString("BinaryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding &apos;{0}&apos; not found. Please enter a correct text encoding or select an encoding from the list..
        /// </summary>
        public static string EncodingNotFound {
            get {
                return ResourceManager.GetString("EncodingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while reading file:
        ///
        ///{0}.
        /// </summary>
        public static string ErrorReading {
            get {
                return ResourceManager.GetString("ErrorReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file.
        ///
        ///{0}.
        /// </summary>
        public static string FailedToOpenFile {
            get {
                return ResourceManager.GetString("FailedToOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        ///
        ///{0}.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Number ({0} – {1}):.
        /// </summary>
        public static string GoTo_PacketNumber {
            get {
                return ResourceManager.GetString("GoTo_PacketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Packet.
        /// </summary>
        public static string GoToPacket {
            get {
                return ResourceManager.GetString("GoToPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file:
        ///
        ///{0}.
        /// </summary>
        public static string LoadingFile {
            get {
                return ResourceManager.GetString("LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LW_Cancel {
            get {
                return ResourceManager.GetString("LW_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string LW_LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LW_LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LW_Title {
            get {
                return ResourceManager.GetString("LW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Network Log Viewer....
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align Panels.
        /// </summary>
        public static string Menu_AlignPanels {
            get {
                return ResourceManager.GetString("Menu_AlignPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Flush Cache.
        /// </summary>
        public static string Menu_AutoDropCache {
            get {
                return ResourceManager.GetString("Menu_AutoDropCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Parse Packets.
        /// </summary>
        public static string Menu_AutoParse {
            get {
                return ResourceManager.GetString("Menu_AutoParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        public static string Menu_CloseFile {
            get {
                return ResourceManager.GetString("Menu_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flush List Cache.
        /// </summary>
        public static string Menu_DropCache {
            get {
                return ResourceManager.GetString("Menu_DropCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Packet....
        /// </summary>
        public static string Menu_GoToPacketN {
            get {
                return ResourceManager.GetString("Menu_GoToPacketN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_LanguageWEn {
            get {
                return ResourceManager.GetString("Menu_LanguageWEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Next Error.
        /// </summary>
        public static string Menu_NextError {
            get {
                return ResourceManager.GetString("Menu_NextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Next Undefined Parser.
        /// </summary>
        public static string Menu_NextUndefinedParser {
            get {
                return ResourceManager.GetString("Menu_NextUndefinedParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Next Unknown Opcode.
        /// </summary>
        public static string Menu_NextUnknownOpcode {
            get {
                return ResourceManager.GetString("Menu_NextUnknownOpcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Protocol).
        /// </summary>
        public static string Menu_NullProtocol {
            get {
                return ResourceManager.GetString("Menu_NullProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Console.
        /// </summary>
        public static string Menu_OpenConsole {
            get {
                return ResourceManager.GetString("Menu_OpenConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Menu_OpenEllipsis {
            get {
                return ResourceManager.GetString("Menu_OpenEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Menu_Plugins {
            get {
                return ResourceManager.GetString("Menu_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        public static string Menu_Protocols {
            get {
                return ResourceManager.GetString("Menu_Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string Menu_RecentFiles {
            get {
                return ResourceManager.GetString("Menu_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Binary Contents....
        /// </summary>
        public static string Menu_SaveBinaryContents {
            get {
                return ResourceManager.GetString("Menu_SaveBinaryContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string Menu_SaveEllipsis {
            get {
                return ResourceManager.GetString("Menu_SaveEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Parser Output....
        /// </summary>
        public static string Menu_SaveParserOutput {
            get {
                return ResourceManager.GetString("Menu_SaveParserOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Text Contents....
        /// </summary>
        public static string Menu_SaveTextContents {
            get {
                return ResourceManager.GetString("Menu_SaveTextContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skins.
        /// </summary>
        public static string Menu_Skins {
            get {
                return ResourceManager.GetString("Menu_Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Panels.
        /// </summary>
        public static string Menu_ViewPanels {
            get {
                return ResourceManager.GetString("Menu_ViewPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Log Viewer.
        /// </summary>
        public static string NetworkLogViewer_Title {
            get {
                return ResourceManager.GetString("NetworkLogViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Data).
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network Log.
        /// </summary>
        public static string NoNetworkLog {
            get {
                return ResourceManager.GetString("NoNetworkLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Protocol.
        /// </summary>
        public static string NoProtocol {
            get {
                return ResourceManager.GetString("NoProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet #{0}.
        /// </summary>
        public static string PacketN {
            get {
                return ResourceManager.GetString("PacketN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing packets....
        /// </summary>
        public static string ParsingPackets {
            get {
                return ResourceManager.GetString("ParsingPackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packets found..
        /// </summary>
        public static string Search_NotFound {
            get {
                return ResourceManager.GetString("Search_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Contents.
        /// </summary>
        public static string SearchBinaryContents {
            get {
                return ResourceManager.GetString("SearchBinaryContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Case.
        /// </summary>
        public static string SearchCase {
            get {
                return ResourceManager.GetString("SearchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow \r, \n, \t, \0.
        /// </summary>
        public static string SearchChars {
            get {
                return ResourceManager.GetString("SearchChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Marks.
        /// </summary>
        public static string SearchClearMarks {
            get {
                return ResourceManager.GetString("SearchClearMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SearchClose {
            get {
                return ResourceManager.GetString("SearchClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string SearchColon {
            get {
                return ResourceManager.GetString("SearchColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string SearchCount {
            get {
                return ResourceManager.GetString("SearchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string SearchDirection {
            get {
                return ResourceManager.GetString("SearchDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Down.
        /// </summary>
        public static string SearchDown {
            get {
                return ResourceManager.GetString("SearchDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchEllipsis {
            get {
                return ResourceManager.GetString("SearchEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot search by opcode with no opcodes provided by the protocol..
        /// </summary>
        public static string SearchFailedNoOpcodes {
            get {
                return ResourceManager.GetString("SearchFailedNoOpcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looped Search.
        /// </summary>
        public static string SearchLoop {
            get {
                return ResourceManager.GetString("SearchLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string SearchMark {
            get {
                return ResourceManager.GetString("SearchMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mode.
        /// </summary>
        public static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify byte sequence you want to find in binary data contained in packets (&apos;Binary Data&apos; tab). Separate hexadecimal digits with spaces, ? or ?? means any byte..
        /// </summary>
        public static string SearchModeDesc_BinaryContents {
            get {
                return ResourceManager.GetString("SearchModeDesc_BinaryContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify opcodes you want to find packets with. You can use opcode name or decimal or hexadecimal opcode value..
        /// </summary>
        public static string SearchModeDesc_Opcodes {
            get {
                return ResourceManager.GetString("SearchModeDesc_Opcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify byte sequence you want to find in packets&apos; data (&apos;Contents&apos; tab). Separate hexadecimal digits with spaces, ? or ?? means any byte..
        /// </summary>
        public static string SearchModeDesc_PacketContents {
            get {
                return ResourceManager.GetString("SearchModeDesc_PacketContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify text you want to find in output of packets&apos; parsers (&apos;Parsed&apos; tab)..
        /// </summary>
        public static string SearchModeDesc_ParserOutput {
            get {
                return ResourceManager.GetString("SearchModeDesc_ParserOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify text you want to find in text data contained in packets (&apos;Text Data&apos; tab)..
        /// </summary>
        public static string SearchModeDesc_TextContents {
            get {
                return ResourceManager.GetString("SearchModeDesc_TextContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Opcodes.
        /// </summary>
        public static string SearchOpcodes {
            get {
                return ResourceManager.GetString("SearchOpcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Contents.
        /// </summary>
        public static string SearchPacketContents {
            get {
                return ResourceManager.GetString("SearchPacketContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser Output.
        /// </summary>
        public static string SearchParserOutput {
            get {
                return ResourceManager.GetString("SearchParserOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Expression.
        /// </summary>
        public static string SearchRegex {
            get {
                return ResourceManager.GetString("SearchRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert string &apos;{0}&apos; to byte sequence..
        /// </summary>
        public static string SearchString2ByteSeqFailed {
            get {
                return ResourceManager.GetString("SearchString2ByteSeqFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert string &apos;{0}&apos; to opcode..
        /// </summary>
        public static string SearchString2OpcodeFailed {
            get {
                return ResourceManager.GetString("SearchString2OpcodeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert string &apos;{0}&apos; to a regular expression..
        /// </summary>
        public static string SearchString2RegexFailed {
            get {
                return ResourceManager.GetString("SearchString2RegexFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Contents.
        /// </summary>
        public static string SearchTextContents {
            get {
                return ResourceManager.GetString("SearchTextContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Up.
        /// </summary>
        public static string SearchUp {
            get {
                return ResourceManager.GetString("SearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamilla Style.
        /// </summary>
        public static string Skin_KamillaStyle {
            get {
                return ResourceManager.GetString("Skin_KamillaStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Style.
        /// </summary>
        public static string Skin_Windows {
            get {
                return ResourceManager.GetString("Skin_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files.
        /// </summary>
        public static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Data.
        /// </summary>
        public static string View_BinaryContents {
            get {
                return ResourceManager.GetString("View_BinaryContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Data #{0}.
        /// </summary>
        public static string View_BinaryContentsN {
            get {
                return ResourceManager.GetString("View_BinaryContentsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while decoding {0}-byte data to string using &apos;{1}&apos; encoding:
        ///
        ///{2}.
        /// </summary>
        public static string View_ErrorDecoding {
            get {
                return ResourceManager.GetString("View_ErrorDecoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while saving text using &apos;{0}&apos; encoding..
        /// </summary>
        public static string View_ErrorEncoding {
            get {
                return ResourceManager.GetString("View_ErrorEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data into file.
        ///
        ///{0}.
        /// </summary>
        public static string View_FailedToSaveIntoFile {
            get {
                return ResourceManager.GetString("View_FailedToSaveIntoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string View_Image {
            get {
                return ResourceManager.GetString("View_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image #{0}.
        /// </summary>
        public static string View_ImageN {
            get {
                return ResourceManager.GetString("View_ImageN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Binary Data.
        /// </summary>
        public static string View_NoBinaryData {
            get {
                return ResourceManager.GetString("View_NoBinaryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Images.
        /// </summary>
        public static string View_NoImages {
            get {
                return ResourceManager.GetString("View_NoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Text Data.
        /// </summary>
        public static string View_NoTextData {
            get {
                return ResourceManager.GetString("View_NoTextData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string View_PacketContents {
            get {
                return ResourceManager.GetString("View_PacketContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed.
        /// </summary>
        public static string View_ParsedText {
            get {
                return ResourceManager.GetString("View_ParsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redecode.
        /// </summary>
        public static string View_Redecode {
            get {
                return ResourceManager.GetString("View_Redecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Data.
        /// </summary>
        public static string View_TextContents {
            get {
                return ResourceManager.GetString("View_TextContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Data #{0}.
        /// </summary>
        public static string View_TextContentsN {
            get {
                return ResourceManager.GetString("View_TextContentsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Object.
        /// </summary>
        public static string View_UnknownObject {
            get {
                return ResourceManager.GetString("View_UnknownObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Object #{0}.
        /// </summary>
        public static string View_UnknownObjectN {
            get {
                return ResourceManager.GetString("View_UnknownObjectN", resourceCulture);
            }
        }
    }
}
