//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkLogViewer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkLogViewer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while reading file:
        ///
        ///{0}.
        /// </summary>
        public static string ErrorReading {
            get {
                return ResourceManager.GetString("ErrorReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file:
        ///
        ///{0}.
        /// </summary>
        public static string LoadingFile {
            get {
                return ResourceManager.GetString("LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LW_Cancel {
            get {
                return ResourceManager.GetString("LW_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait....
        /// </summary>
        public static string LW_LoadingPleaseWait {
            get {
                return ResourceManager.GetString("LW_LoadingPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LW_Title {
            get {
                return ResourceManager.GetString("LW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Network Log Viewer....
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close File.
        /// </summary>
        public static string Menu_CloseFile {
            get {
                return ResourceManager.GetString("Menu_CloseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Menu_LanguageWEn {
            get {
                return ResourceManager.GetString("Menu_LanguageWEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Protocol).
        /// </summary>
        public static string Menu_NullProtocol {
            get {
                return ResourceManager.GetString("Menu_NullProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Console.
        /// </summary>
        public static string Menu_OpenConsole {
            get {
                return ResourceManager.GetString("Menu_OpenConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Menu_OpenEllipsis {
            get {
                return ResourceManager.GetString("Menu_OpenEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocols.
        /// </summary>
        public static string Menu_Protocols {
            get {
                return ResourceManager.GetString("Menu_Protocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string Menu_SaveEllipsis {
            get {
                return ResourceManager.GetString("Menu_SaveEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skins.
        /// </summary>
        public static string Menu_Skins {
            get {
                return ResourceManager.GetString("Menu_Skins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Panels.
        /// </summary>
        public static string Menu_ViewPanels {
            get {
                return ResourceManager.GetString("Menu_ViewPanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Log Viewer.
        /// </summary>
        public static string NetworkLogViewer_Title {
            get {
                return ResourceManager.GetString("NetworkLogViewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Data).
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network Log.
        /// </summary>
        public static string NoNetworkLog {
            get {
                return ResourceManager.GetString("NoNetworkLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Protocol.
        /// </summary>
        public static string NoProtocol {
            get {
                return ResourceManager.GetString("NoProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamilla Style.
        /// </summary>
        public static string Skin_KamillaStyle {
            get {
                return ResourceManager.GetString("Skin_KamillaStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Style.
        /// </summary>
        public static string Skin_Windows {
            get {
                return ResourceManager.GetString("Skin_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Data.
        /// </summary>
        public static string View_BinaryContents {
            get {
                return ResourceManager.GetString("View_BinaryContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string View_Image {
            get {
                return ResourceManager.GetString("View_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string View_PacketContents {
            get {
                return ResourceManager.GetString("View_PacketContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed.
        /// </summary>
        public static string View_ParsedText {
            get {
                return ResourceManager.GetString("View_ParsedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Data.
        /// </summary>
        public static string View_TextContents {
            get {
                return ResourceManager.GetString("View_TextContents", resourceCulture);
            }
        }
    }
}
