//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamilla.Network.Protocols.Wow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WowStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WowStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kamilla.Network.Protocols.Wow.WowStrings", typeof(WowStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Classes.
        /// </summary>
        internal static string AllClasses {
            get {
                return ResourceManager.GetString("AllClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance Races.
        /// </summary>
        internal static string AllianceRaces {
            get {
                return ResourceManager.GetString("AllianceRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Races.
        /// </summary>
        internal static string AllRaces {
            get {
                return ResourceManager.GetString("AllRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrior.
        /// </summary>
        internal static string Class1 {
            get {
                return ResourceManager.GetString("Class1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string Class11 {
            get {
                return ResourceManager.GetString("Class11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        internal static string Class2 {
            get {
                return ResourceManager.GetString("Class2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        internal static string Class3 {
            get {
                return ResourceManager.GetString("Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string Class4 {
            get {
                return ResourceManager.GetString("Class4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priest.
        /// </summary>
        internal static string Class5 {
            get {
                return ResourceManager.GetString("Class5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Knight.
        /// </summary>
        internal static string Class6 {
            get {
                return ResourceManager.GetString("Class6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaman.
        /// </summary>
        internal static string Class7 {
            get {
                return ResourceManager.GetString("Class7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mage.
        /// </summary>
        internal static string Class8 {
            get {
                return ResourceManager.GetString("Class8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        internal static string Class9 {
            get {
                return ResourceManager.GetString("Class9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft (Classic).
        /// </summary>
        internal static string Expac0 {
            get {
                return ResourceManager.GetString("Expac0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft: The Burning Crusade.
        /// </summary>
        internal static string Expac1 {
            get {
                return ResourceManager.GetString("Expac1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft: Wrath of the Lich King.
        /// </summary>
        internal static string Expac2 {
            get {
                return ResourceManager.GetString("Expac2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft: Cataclysm.
        /// </summary>
        internal static string Expac3 {
            get {
                return ResourceManager.GetString("Expac3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World of Warcraft: Mists of Pandaria.
        /// </summary>
        internal static string Expac4 {
            get {
                return ResourceManager.GetString("Expac4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender0 {
            get {
                return ResourceManager.GetString("Gender0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender1 {
            get {
                return ResourceManager.GetString("Gender1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Gender2 {
            get {
                return ResourceManager.GetString("Gender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horde Races.
        /// </summary>
        internal static string HordeRaces {
            get {
                return ResourceManager.GetString("HordeRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Classes.
        /// </summary>
        internal static string NoClasses {
            get {
                return ResourceManager.GetString("NoClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Races.
        /// </summary>
        internal static string NoRaces {
            get {
                return ResourceManager.GetString("NoRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Not Playable Races.
        /// </summary>
        internal static string NotPlayableRaces {
            get {
                return ResourceManager.GetString("NotPlayableRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Playable Races.
        /// </summary>
        internal static string PlayableRaces {
            get {
                return ResourceManager.GetString("PlayableRaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string Race1 {
            get {
                return ResourceManager.GetString("Race1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Elf.
        /// </summary>
        internal static string Race10 {
            get {
                return ResourceManager.GetString("Race10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draenei.
        /// </summary>
        internal static string Race11 {
            get {
                return ResourceManager.GetString("Race11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel Orc.
        /// </summary>
        internal static string Race12 {
            get {
                return ResourceManager.GetString("Race12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naga.
        /// </summary>
        internal static string Race13 {
            get {
                return ResourceManager.GetString("Race13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        internal static string Race14 {
            get {
                return ResourceManager.GetString("Race14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton.
        /// </summary>
        internal static string Race15 {
            get {
                return ResourceManager.GetString("Race15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrykul.
        /// </summary>
        internal static string Race16 {
            get {
                return ResourceManager.GetString("Race16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuskarr.
        /// </summary>
        internal static string Race17 {
            get {
                return ResourceManager.GetString("Race17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Troll.
        /// </summary>
        internal static string Race18 {
            get {
                return ResourceManager.GetString("Race18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taunka.
        /// </summary>
        internal static string Race19 {
            get {
                return ResourceManager.GetString("Race19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        internal static string Race2 {
            get {
                return ResourceManager.GetString("Race2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northrend Skeleton.
        /// </summary>
        internal static string Race20 {
            get {
                return ResourceManager.GetString("Race20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Troll.
        /// </summary>
        internal static string Race21 {
            get {
                return ResourceManager.GetString("Race21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worgen.
        /// </summary>
        internal static string Race22 {
            get {
                return ResourceManager.GetString("Race22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gilneas Human.
        /// </summary>
        internal static string Race23 {
            get {
                return ResourceManager.GetString("Race23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        internal static string Race3 {
            get {
                return ResourceManager.GetString("Race3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Elf.
        /// </summary>
        internal static string Race4 {
            get {
                return ResourceManager.GetString("Race4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        internal static string Race5 {
            get {
                return ResourceManager.GetString("Race5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tauren.
        /// </summary>
        internal static string Race6 {
            get {
                return ResourceManager.GetString("Race6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        internal static string Race7 {
            get {
                return ResourceManager.GetString("Race7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll.
        /// </summary>
        internal static string Race8 {
            get {
                return ResourceManager.GetString("Race8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblin.
        /// </summary>
        internal static string Race9 {
            get {
                return ResourceManager.GetString("Race9", resourceCulture);
            }
        }
    }
}
